# Generated by Django 3.2.12 on 2024-02-21 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionModel',
            fields=[
                ('action_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ActivesModel',
            fields=[
                ('active_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('active_name', models.TextField(max_length=100)),
                ('now_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPairsModel',
            fields=[
                ('pair_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pair_mame', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenerModel',
            fields=[
                ('screener_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('screener_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SourceModel',
            fields=[
                ('source_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source_name', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BriefcaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.DecimalField(decimal_places=2, max_digits=10000000)),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.actionmodel')),
                ('active_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.activesmodel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activesmodel',
            name='pair_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.currencypairsmodel'),
        ),
        migrations.AddField(
            model_name='activesmodel',
            name='screener_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.screenermodel'),
        ),
        migrations.AddField(
            model_name='activesmodel',
            name='source_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sourcemodel'),
        ),
    ]
