# Generated by Django 3.2.12 on 2024-02-24 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0002_alter_activesmodel_now_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BriefcaseModel',
            new_name='HistoryModel',
        ),
    ]
